<?php
require_once "lib/Debug.php";
use proven\lib\debug;
debug\Debug::iniset();

require_once "model/Product.php";
require_once "model/Warehouse.php";
require_once "model/StoreModel.php";

use proven\store\model\StoreModel;
use proven\store\model\Product;
use proven\store\model\Warehouse;

$model = new StoreModel();


echo "    /* ============== USER  METHODS ============== */";
echo "<br/>";
echo 'find all users';
echo "<br>";
debug\Debug::display($model->findAllUsers());
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br>";
echo 'find users by role = admin';
echo "<br>";
debug\Debug::display($model->findUsersByRole("admin"));
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br>";
echo 'find users by role = staff';
echo "<br>";
debug\Debug::display($model->findUsersByRole("staff"));
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br>";
echo 'find users by id = 1';
echo "<br>";
debug\Debug::objectprint($model->findUserById(1));
echo "<br>";
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br/>";
echo "    /* ============== CATEGORIES  METHODS ============== */";
echo "<br>";
echo 'find all categories';
echo "<br>";
debug\Debug::display($model->findAllCategories());
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br>";
echo 'find category by code = catcode01';
echo "<br>";
debug\Debug::display($model->findCategoryByCode("catcode01"));
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br>";
echo 'find category by code = catcode02';
echo "<br>";
debug\Debug::display($model->findCategoryByCode("catcode02"));
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br>";
echo 'find category by id = 1';
echo "<br>";
debug\Debug::objectprint($model->findCategoryById(1));
echo "<br/>";
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br/>";
echo "    /* ============== PRODUCTS METHODS ============== */";
echo "<br>";
echo 'find all products';
echo "<br>";
debug\Debug::display($model->findAllProducts());
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br>";
echo 'find product by category id = 1';
echo "<br>";
debug\Debug::display($model->findProductByCategoryId(1));
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br>";
echo 'find product by categorycode = catcode02';
echo "<br>";
debug\Debug::display($model->findProductByCategoryCode("catcode02"));
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br>";
echo 'find product by id = 1';
echo "<br>";
debug\Debug::objectprint($model->findProductById(1));
echo "<br/>";
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br/>";
echo "    /* ============== WAREHOUSE METHODS ============== */";
echo "<br>";
echo 'find all warehouse';
echo "<br>";
debug\Debug::display($model->findAllWarehouse());
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br>";
echo 'find warehouse by id = 1';
echo "<br>";
debug\Debug::objectprint($model->findWarehouseById(1));
echo "<br/>";
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br/>";
echo "    /* ============== WAREHOUSEPRODUCTS METHODS ============== */";
echo "<br>";
echo 'find all warehouseproducts';
echo "<br>";
debug\Debug::display($model->findAllWarehouseProduct());
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br>";
echo 'find warehouseproducts by warehouseid = 1';
echo "<br>";
debug\Debug::display($model->findWarehouseProductByWarehouse_id(1));
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br>";
echo 'find warehouseproducts by productid = 3';
echo "<br>";
debug\Debug::display($model->findWarehouseProductByProduct_id(3));
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br>";
echo 'find warehouse code by productid = 3';
echo "<br>";
debug\Debug::display($model->getwarehousecodes(3));
echo '----------------------------------------------------------------------------------------------------------------------------------';
echo "<br>";
echo 'find producr code by warehouseid = 1';
echo "<br>";
debug\Debug::display($model->getproductscodes(1));
echo "<br/>";